# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3566b1531bad62194f173838fd35246090eda4c73606a1c53efb7d552e1ad6516465a452dcc2b794216d08b58f89bd0dad471ee7802f7dffa0822be1c3d29d30

test:
  secret_key_base: 47e61baeb96fa55329d1275d05acc80f6021c65571ff77b877d64183a9fedb3ed61116763ed3fde9139964e879120bed33ef72f96dea47f0b790c21652763b3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
